### ISSUE TITLE
Add settings menu

### ISSUE THREAD

**Issue by Hubza** [Team-Cubey/cubey-issues#12]
- [x] implement settings menu
- [x] implement volume sliders for music & volume in settings menu

**Comment by CubeyJohs** [comment]
YES!!!!!

**Comment by rhythm-on-github** [comment]
!!!!!!

**Comment by Hubza** [comment]
!

**Comment by Hubza** [comment]
considering putting it next to the info button in the top right, just a little gear. would like to know what people think of that

**Comment by rhythm-on-github** [comment]
seems good

**Comment by Hubza** [comment]
i want to try to make options an overlay of sorts, instead of another screen overall, but im not sure where to put it other than the center. heres a little concept i put together, you'd be able to scroll the panel up and down if it gets too big in the future
![image](https://user-images.githubusercontent.com/33783503/97328996-7ac2fb80-186e-11eb-9784-0c2bd7c5b485.png)

**Comment by dheerajhyper69** [comment]
> i want to try to make options an overlay of sorts, instead of another screen overall, but im not sure where to put it other than the center. heres a little concept i put together, you'd be able to scroll the panel up and down if it gets too big in the future
> ![image](https://user-images.githubusercontent.com/33783503/97328996-7ac2fb80-186e-11eb-9784-0c2bd7c5b485.png)

Yes this is nice, pretty much exactly what I asked for! (if the nonexistence of a settings button was indeed intended for this early preview)

**Comment by Hubza** [comment]
it was just a quick mockup in adobe xd, nothing special, no functionality or anything
![image](https://user-images.githubusercontent.com/33783503/97329955-87941f00-186f-11eb-8a37-5bd563d425b4.png)

**Comment by Hubza** [comment]
![image](https://user-images.githubusercontent.com/33783503/97331016-cd9db280-1870-11eb-94c3-d135844b09c6.png)
for anyone interested this was the original proposal of the design

**Comment by dheerajhyper69** [comment]
I like the first one better tbh

**Comment by Hubza** [comment]
meaning the old proposal or the one i posted a while ago

this one (the one i just posted) is the old one from around 2 months ago

**Comment by dheerajhyper69** [comment]
> meaning the old proposal or the one i posted a while ago
> 
> this one (the one i just posted) is the old one from around 2 months ago

I like the one in the adobe xd window (the first on on THIS thread): [this one](https://github.com/Team-Cubey/cubey-issues/issues/12#issuecomment-717354614)

**Comment by Hubza** [comment]
ah that one, yeah thats the newest one i put together today

**Comment by Hubza** [comment]
not sure how to go about this, will most likely make it a flexable system with prefabs for checkboxes/radio buttons & sliders which i can just drag in and assign to a variable. i want to make the code of the game flexible so this will take some time.

**Comment by rhythm-on-github** [comment]
Maybe also make it able to have >1 tab, in case many settings get added

**Comment by Hubza** [comment]
it's scrollable.

**Comment by rhythm-on-github** [comment]
ok, but if there's going to be more than like 2 "pages" of settings at some point, it might be nice to separate it into tabs xd

**Comment by Hubza** [comment]
![image](https://user-images.githubusercontent.com/33783503/97353793-63930680-188c-11eb-8595-58852e0e2c64.png)

**Comment by rhythm-on-github** [comment]
Also nice

**Comment by Hubza** [comment]
![image](https://user-images.githubusercontent.com/33783503/97464387-c17d2800-1938-11eb-9b6b-321a2d8ff1e3.png)
ingame implementation so far

**Comment by dheerajhyper69** [comment]
Yes!
