### ISSUE TITLE
Make it big screen on startup

### ISSUE THREAD

**Issue by rhythm-on-github** [Team-Cubey/cubey-issues#13]
I think the game should start up in "fullscreen" mode (not true fullscreen, just not small window)

Not sure if it's specific to my system though - for me, it always starts in a window that is about the same size as my screen, but in small window mode

(notice how it is slightly offset)
![image](https://user-images.githubusercontent.com/57626311/97227069-3d5e5f80-17d5-11eb-9c1a-ac4cadfff64b.png)

**Comment by Hubza** [comment]
it copies your last size. from my knowledge i cant auto maximize it. for now you can use ALT+ENTER

**Comment by rhythm-on-github** [comment]
ok, thanks. However, without ALT+ENTER it doesn't remember the last size.

**Comment by Hubza** [comment]
fixed
