### ISSUE TITLE
Key hitbox "randomness" (rotating hitbox)

### ISSUE THREAD

**Issue by rhythm-on-github** [Team-Cubey/cubey-issues#19]
With how key hitboxes are currently handled, the distance at which you can pick them up feels kinda random imo. It's not a huge deal, but i think it would be nicer for it to be a cubic, non-rotating hitbox.

With that said, the 2nd level in Precision Pack might need to be revised if this does get changed.

**Comment by Hubza** [comment]
this will not be fixed.

**Comment by rhythm-on-github** [comment]
F :(
