### ISSUE TITLE
Softlock with turrets

### ISSUE THREAD

**Issue by rhythm-on-github** [Team-Cubey/cubey-issues#6]
Ok so this softlock is pretty specific. The circumstances are:
-being 1 block to the (left/right) of a turret
-being 1 block above it
-having a ceiling 1 block above yourself
-the turret turning in just the "wrong" way

In this scenario, you can get completely stuck and will get killed by the turret.
I was jumping over the turret but kinda failed

**Comment by Hubza** [comment]
how do you get stuck

**Comment by Hubza** [comment]
a video would help

**Comment by rhythm-on-github** [comment]
![image](https://user-images.githubusercontent.com/57626311/97223947-bf985500-17d0-11eb-898a-dd24dfeac201.png)
here's an (edited) image showing it

**Comment by Hubza** [comment]
seems like the turret shaft/barrel (shaft in code) is moving the player to a place where he cant move. will fix by just removing the collider.
